### ISSUE TITLE
stomp precompilation broken

### ISSUE THREAD

**Issue by carbin** [niner/Inline-Perl5#10]
[stomp](https://github.com/carbin/stomp) uses Inline::Perl5 to call some Perl 5 modules (mainly Crypt::CBC) and has been precompiling fine but it now fails as of https://github.com/niner/Inline-Perl5/commit/555fb84960c4f8ba4a5d27eac8605a9b9f6ab7c3

    $ panda-build  
    Compiling lib/Stomp/Crypt.pm6 to mbc
    Compiling lib/Stomp/Config.pm6 to mbc
    Compiling lib/Stomp/Exception.pm6 to mbc
    Compiling lib/Stomp/Utils.pm6 to mbc
    ===SORRY!===
    Missing serialize REPR function for REPR CPointer

Works fine with 546bd09dccf.

**Comment by niner** [comment]
Inline::Perl5 now has "no precompilation;" so using it should be safe. We will upgrade to "no precompilation 'users';" once that's implemented in rakudo.

Precompiling users of Inline::Perl5 will be a hard thing to fix, since we'd need to serialize the Perl 5 interpreter's state alongside the precompiled Perl 6 code.
