### ISSUE TITLE
Concurrency and Object::Result

### ISSUE THREAD

**Issue by agoetschm** [niner/Inline-Perl5#133]
Hi,

I'm trying do use multiple instances of Inline::Perl5 in separate threads as suggested in #94, but it crashes when I try to use [Object::Result](https://metacpan.org/pod/Object::Result). 
```
➜ ls
a                   test-concurrency.p6
```
```
➜  cat a/b.pm
package a::b;

use 5.010;
use strict;
use warnings;

use Object::Result;

use Exporter 'import';
our @EXPORT_OK = qw( x );

sub x {
    say "I'm x";
}
```
```
➜  cat test-concurrency.p6
#!/usr/bin/env perl6

use Inline::Perl5;

my $fun = sub ($p5, $inst) {
    for 1..10 {
        say "fun $inst";
        $p5.run("x()");
        sleep 0.1;
    }
};

my $p5_1 = Inline::Perl5.new;
$p5_1.run("use lib '.'");
$p5_1.run("use a::b qw(x)");
my $first = start {
    say "a";
    $fun($p5_1, 1);
};

my $p5_2 = Inline::Perl5.new;
$p5_2.run("use lib '.'");
say 'before';
$p5_2.run("use a::b qw(x)");
say 'after';
my $second = start {
    say "b";
    $fun($p5_2, 2);
};

await($first);
await($second);
```
```
➜  perl6 test-concurrency.p6
a
fun 1
I'm x
before
fun 1

```

And it hangs. This doesn't happen if I comment `use Object::Result`, any idea why this is happening?

Thanks in advance!

**Comment by niner** [comment]
@agoetschm instead of the process hanging I get a segfault apparently due to an endless recursion involving `my_keyword_plugin` from Keyword::Simple. It uses `PL_keyword_plugin` of which the perlapi documentation says "Direct access to "PL_keyword_plugin" should be avoided" (due to threading issues). So this looks rather like a bug in `Keyword::Simple`. Can you please report it there?

**Comment by kbucheli** [comment]
Thank you for the insights, I opened https://rt.cpan.org/Ticket/Display.html?id=131038
