### ISSUE TITLE
Latest version throws the a library not found

### ISSUE THREAD

**Issue by Xliff** [niner/Inline-Perl5#149]
The error:

```
===SORRY!=== Error while compiling /home/cbwood/Projects/p6-GStreamer/scripts/prop-gen-gstreamer.pl6
===SORRY!=== Error while compiling /home/cbwood/Projects/p6-GStreamer/site#sources/46A21D2AC9383D74F5E3CE760D84D29F9009C6B8 (Inline::Perl5)
===SORRY!=== Error while compiling /home/cbwood/Projects/p6-GStreamer/site#sources/0F50B574622C7F9833911E194CCEAFFE83348161 (Inline::Perl5::Interpreter)
An exception occurred while evaluating a constant
at /home/cbwood/Projects/p6-GStreamer/site#sources/0F50B574622C7F9833911E194CCEAFFE83348161 (Inline::Perl5::Interpreter):12
Exception details:
  ===SORRY!=== Error while compiling 
  Cannot locate native library '(null)': libperl.so.5.28: cannot open shared object file: No such file or directory
  at :

at /home/cbwood/Projects/p6-GStreamer/site#sources/46A21D2AC9383D74F5E3CE760D84D29F9009C6B8 (Inline::Perl5):5
```

This might have something to do with the fact that Kubuntu Focal Fossa has standardized on libperl5.5.26 and libperl5.5.30, but not libperl5.5.28.

My Environment:

Perl
```
This is Rakudo version 2020.02.1-386-g6bb87106e built on MoarVM version 2020.02.1-163-g8b109c68b implementing Raku 6.d
```

Linux
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
```

**Comment by niner** [comment]
When you upgrade perl, you need to re-install Inline::Perl5 as well.

**Comment by Xliff** [comment]
Ahh... mea culpa.

**Comment by bo-tato** [comment]
I also was confused for a bit after upgrading perl before realizing I needed to re-install Inline::Perl5 to get it working again. It first gave error that libperl.so not found (without a version number), so I manually added the directory with libperl.so to my LD_LIBRARY_PATH, then it caused segfaults, then I reinstall Inline::Perl5 and everything's working. Maybe this could print a better error message like "couldn't find expected version of libperl.so, maybe you upgraded perl and need to reinstall Inline::Perl5"?

**Comment by raiph** [comment]
Hi @bo-tato 

Please redirect your attention to [this issue](https://github.com/rakudo/rakudo/issues/2101).

(I don't think you need to do anything. I think the link I just wrote should result in a link back to this one, so you don't need to comment. But that issue will be where any action able to address this must begin.)

----

In case a bit more info helps...

This situation is at least [LTA](https://docs.raku.org/language/glossary#LTA). That's part of the reason for my ❤. (Another part is empathy for the confusion, segfaults etc process.)

The LTA error message is generated by IP5 dependency [NativeCall](https://docs.raku.org/language/modules-core#Core_modules), NC for short, so it's NC that needs to change, or more accurately it's NC that needs to change first.

The problem of the error message being LTA is much broader than it being LTA for IP5. NC is used by a lot of libraries. So any solution to this problem will need to be based on NC having better error messages and/or making it possible for its clients to customize its error messages, or at least this one.

NC is shipped with the Raku compiler implementation Rakudo. I [searched its repo for "cannot locate"](https://github.com/search?q=repo%3Arakudo%2Frakudo%20%22cannot%20locate%22) and that's how I discovered the related issue I linked above: [`LTA NativeCall error message - "Cannot locate native library 'libssl.so'" has no file/line`](https://github.com/rakudo/rakudo/issues/2101).

The issue was opened in 2018. While I think they have improved the error message since then, it remains open, presumably because it's recognized that clients such as IP5 need there to be better error messages than a plain "Cannot locate foo".

Its latest tag (`Will be addressed in RakuAST`) was added by lizmat a month ago. There's good reason to anticipate RakuAST arriving at or near shipping during 2025. So there's good reason to think this error message will improve by then or perhaps in 2026.

Thanks for commenting!
