### ISSUE TITLE
Compile error when loading the same module across interpreters

### ISSUE THREAD

**Issue by ab5tract** [niner/Inline-Perl5#27]
There is something in the role composition which breaks `.use`, though `.run('use ...;')` works as expected.

```perl6
> use Inline::Perl5
> my @p; @p.push: Inline::Perl5.new xx 10
> @p>>.use('File::Temp')
===SORRY!=== Error while compiling EVAL_2
Redeclaration of symbol File::Temp
at EVAL_2:1
------> le::Temp does Perl5Package[$p5, $module]⏏ { }
> @p>>.invoke('File::Temp','new')
Can't locate object method "new" via package "File::Temp" (perhaps you forgot to load "File::Temp"?).

  in method invoke at lib/Inline/Perl5.pm6:483
  in block <unit> at <unknown file>:1

> @p>>.run('use File::Temp;')
> @p>>.invoke('File::Temp','new')  #works now
```

**Comment by niner** [comment]
Fixed with commits 871858dfa21565737df46fc86c0197a95ef34237 and 07dd4fb7500178edbb43e4f26fe75935e573551e

Only the first created Inline::Perl5 object tries to create the Perl 6 wrappers for Perl 5 modules now. And it's now possible to load the same module mutliple times on the same interpreter (just like multiple use statements for the same module in Perl 5 or 6) without conflict.
