### ISSUE TITLE
Using local::lib with a relative path doesn't seem to work

### ISSUE THREAD

**Issue by hoelzro** [niner/Inline-Perl5#29]
For example:

``` perl6
use Inline::Perl5;
BEGIN EVAL "use local::lib 'p5lib'", :lang<perl5>;
use XML::Twig:from<Perl5>;
```

gives me the error

```
Attempting to create directory /p5lib/
===SORRY!===
Can't locate XML/Twig.pm in @INC (you may need to install the XML::Twig module) (@INC contains: /p5lib
/lib/perl5/5.22.0/x86_64-linux-thread-multi /p5lib/lib/perl5/5.22.0 /p5lib/lib/perl5/x86_64-linux-thread-multi /p5lib
/lib/perl5 /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl 
/usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at (eval 1) line 71.
BEGIN failed--compilation aborted.
```

Using an absolute path with `local::lib` works fine.

**Comment by niner** [comment]
This is actually a bug in `local::lib` which simply doesn't work when the Perl interpreter is embedded in an executable that has "perl" somewhere in the name. The bug lies in the _perl function which probably should trust $Config::Config{perlpath} more than $^X just like perlvar(1) recommends.

Incidentally this will be taken care of by the rename to Raku.
