### ISSUE TITLE
reference counting

### ISSUE THREAD

**Issue by daxim** [niner/Inline-Perl5#45]
https://news.ycombinator.com/item?id=10349688

test program
------------

    use v6;
    use Inline::Perl5;
    use ReleaseAction:from<Perl5> 'on_release';
    say "1..6";
    say "ok 1";

    {
        my $handle = ReleaseAction.new(-> { say "ok 3" });
        say "ok 2";
    }

    {
        my $handle = on_release(-> { .say }, "ok 5");
        say "ok 4";
    }

    {
        my $handle = on_release(-> { print "not " });
        $handle.cancel();
    }
    say "ok 6";

expected
--------

    1..6
    ok 1
    ok 2
    ok 3
    ok 4
    ok 5
    ok 6

actual
------

    1..6
    ok 1
    ok 2
    ok 4
    ok 6

**Comment by niner** [comment]
The linked comments already explain that this is just a difference between Perl 5 and Perl 6. Perl 6 does not guarantee running destructors in a timely fashion and indeed, it does not even guarantee running them at all. That's by design. Perl 5 actually doesn't guarantee it either: POSIX::_exit is one counter example.

A module like ReleaseAction is obsolete in Perl 6 anyway, since Perl 6 already provides the LEAVE phaser for the same purpose. There's no reason to use ReleaseAction in Perl 6, hence I don't see a problem. It's in the same bucket as most modules in the Perl6:: namespace.

The comments mention DBIx::Class, Moose, and Catalyst. I have already tested and used all of those with Inline::Perl5. Now if one of those were to use a module like ReleaseAction internally, that would still work.
