### ISSUE TITLE
Dependency on panda?

### ISSUE THREAD

**Issue by zoffixznet** [niner/Inline-Perl5#61]
Hey,

I was just curious whether the [dependency on panda](https://github.com/niner/Inline-Perl5/blob/master/META.info#L10) is really needed.

I tend to use [`zef`](http://modules.perl6.org/repo/zef), so I'm kind of bummed to see installing Inline::Perl5 brought in panda and all of its deps in as well.

**Comment by niner** [comment]
Removed the cargo culted build dependency in commit c0fd19a29998d2053164094b7b9893637d3ae67f

Thanks for the report!

**Comment by ugexe** [comment]
https://github.com/niner/Inline-Perl5/blob/master/Build.pm#L2
https://github.com/niner/Inline-Perl5/blob/master/Build.pm#L6

zef makes it work anyway by modifying the `Build.pm` when it can get away with it, which is essentially a requirement because no one declares(ed) their build-deps. See https://github.com/titsuki/p6-Terminal-Readsecret/blob/master/Build.pm for a true package manager-less `Build.pm`
