### ISSUE TITLE
Automatically Convert Kebob-Case to Snake-Case

### ISSUE THREAD

**Issue by zoffixznet** [niner/Inline-Perl5#67]
I've no idea what's possible, but it'd be nice if the module automatically converted kebob-cased methods from Perl 6 into snake_case in Perl 5.

I'm currently using Mojolicious and despite always using kebob-case in my Perl 6 code, I have to change to snake_case any methods I plan on using inside the EP templates. This is even more inconvenient with the kebob-cased methods on core Perl 6 objects exposed to Perl 5.

**Comment by vendethiel** [comment]
(It's [kebab-case](http://c2.com/cgi/wiki?KebabCase).)

**Comment by zoffixznet** [comment]
> (It's kebab-case.)

Tom-ay-to/tom-ah-to  [http://www.dictionary.com/browse/kebob](http://www.dictionary.com/browse/kebob)

**Comment by niner** [comment]
Perhaps not widely known, but there's actually a way to call arbitrarily named methods even in Perl 5:

> perl6 -e 'use Inline::Perl5; EVAL q/sub call_back { my $name = "test-me"; $_[0]->$name(); }/, :lang<Perl5>; Inline::Perl5.default_perl5.call("call_back", class :: { method test-me() { say "test-me called!" } }.new)'
test-me called!

This makes me reluctant to play around with method names. Also it's quite possible for a Perl 6 class to have both a foo-bar and a foo_bar method.

Besides, since we look up methods at the time they are called, we'd have to first look for a foo_bar and if we don't find one try again with foo-bar. And what's with mixed use? A method could be named get_foo-bar. We'd have to try all permutations to find that one.
