### ISSUE TITLE
Algorithm::LibLinear.predict method returns the error message of "free(): invalid next size (fast)"

### ISSUE THREAD

**Issue by titsuki** [niner/Inline-Perl5#79]
Hi
See the following results:

## Code
```
use Algorithm::LibLinear:from<Perl5>;
use Algorithm::LibLinear::DataSet:from<Perl5>;

my $data-str = q:to/END/;
1 1:0.1 2:0.1 4:0.1
-1 1:0.1 2:-0.1 3:0.1
END

my $data-set = Algorithm::LibLinear::DataSet.load(string => $data-str);
my $learner = Algorithm::LibLinear.new;
my $classifier = $learner.train(data_set => $data-set);
my $label = $classifier.predict(feature => { 1 => 0.3e0, 2 => 0.4e0, 3 => 0.5e0, 4 => 0.2e0});
$label.say;
````

## Error  ("中止" means "halt" in English)
```
*** Error in `/home/itoyota/.rakudobrew/moar-nom/install/bin/moar': free(): invalid next size (fast): 0x0000000004138ed0 ***
中止
```

## Version
```
$ perl6 --version
This is Rakudo version 2016.11-105-gae614f9 built on MoarVM version 2016.11-25-g4be6b38
implementing Perl 6.c.
```
```
$ perl --version

This is perl 5, version 24, subversion 0 (v5.24.0) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2016, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

+ Algorithm::LibLinear is verson 0.16

## See also:

+ Algorithm::LibLinear ( version 0.16 ) 
    + http://search.cpan.org/~sekia/Algorithm-LibLinear/lib/Algorithm/LibLinear.pm

**Comment by niner** [comment]
Hi! Thanks for the report.
I'd argue that this is a bug in Algorithm::LibLinear. It doesn't seem to deal correctly with tied hashes.
By changing your example code to this, the error disappears:
`my $label = $classifier.predict(feature => Map.new((1 => 0.3e0, 2 => 0.4e0, 3 => 0.5e0, 4 => 0.2e0)));`

When Perl 6 hashes get passed to Perl 5 code, they get wrapped by a tied hash on the Perl 5 side, so when you write to the Perl 5 hash, the Perl 6 hash will be updated, too.
As Maps are immutable hashes, we don't need support for updates, so the Map's contents will be copied to a plain Perl 5 hash. That's why the version with Map just works. 

I'd bet that the same bug is reproducible in plain Perl 5 by passing a tied hash to $classifier->predict.

**Comment by titsuki** [comment]
@niner
Thanks for your reply !
I'll try it later and reports the results.

**Comment by titsuki** [comment]
@niner 
Thanks! It works fine !!!
http://qiita.com/titsuki/items/ab4f78d6b7be7f4f6baa
